# Sets the strings to be blocked
blocked-strings = ["exception", "etc"]

# Sets whether a regex detection will be performed.
# If this option is set to false it will check
# if the console messages contain any string
# specified in blocked-strings, otherwise
# it will do regex checks according to
# blocked-strings to each console message.
use-regex = false